server:
  port: 7000
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create    #create in dev
      #ddl-auto: update   update in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

